#! /usr/bin/env python3

from pyrser.grammar import Grammar
from pyrser import meta
from cnorm.parsing.declaration import Declaration
from cnorm.passes import to_c
import sys

class TestCnorm(Grammar, Declaration):
    entry = 'translation_unit'

if len(sys.argv) is not 2:
        print("Usage : " + sys.argv[0] + " FILE")
        sys.exit()

testCnorm = TestCnorm()
res = testCnorm.parse_file(sys.argv[1])

print (res.to_yml())
#print (res.to_c())
