#! /usr/bin/env python3
# Kooc main program

from kooc import Kooc
from cnorm.passes import to_c
import kooc_validity
import kooc_typage
import sys


def parse_kooc(inputfile):
    outputfile = kooc_validity.check(inputfile)
    if outputfile == "ERROR":
        sys.exit()
    kooc = Kooc(sys.argv[1])
    res = kooc.parse_file(sys.argv[1])
    print (res.to_yml())
    res = kooc_typage.typage(res, kooc.koocdata.typeList)
    print (res.to_yml())
    print (res.to_c())
    # TODO : ecrire dans un ficher serait pas mal....
    filename = open(outputfile ,"w+")
    filename.write(str(res.to_c()))
    filename.close()


if len(sys.argv) is not 2:
    print("Usage : " + sys.argv[0] + " FILE")
    sys.exit()

parse_kooc(sys.argv[1])
